import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex gap-4 p-4">
          <Link
            href="/"
            className="px-3 py-1 border rounded-md shadow-sm hover:bg-gray-10"
          >
            Home
          </Link>
          <Link
            href="/about"
            className="px-3 py-1 border rounded-md shadow-sm hover:bg-gray-10"
          >
            About
          </Link>
          <Link
            href="/contact"
            className="px-3 py-1 border rounded-md shadow-sm hover:bg-gray-10"
          >
            Contact
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
