// app/layout.tsx  (SERVER component — do NOT add "use client")
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { readSession } from "@/lib/auth";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await readSession();

  // 👇 Inline server action (works even if this file accidentally becomes client)
  async function logout() {
    "use server";
    const { clearSession } = await import("@/lib/auth"); // dynamic import is server-only here
    await clearSession();
  }

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {session && (
          <div className="flex items-center gap-4 p-4 border-b">
            <Link href="/" className="px-3 py-1 border rounded-md shadow-sm hover:bg-gray-10">Home</Link>
            <Link href="/about" className="px-3 py-1 border rounded-md shadow-sm hover:bg-gray-10">About</Link>
            <Link href="/contact" className="px-3 py-1 border rounded-md shadow-sm hover:bg-gray-10">Contact</Link>
            <Link href="/users" className="px-3 py-1 border rounded-md shadow-sm hover:bg-gray-10">Users</Link>
            <Link href="/groups" className="px-3 py-1 border rounded-md shadow-sm hover:bg-gray-10">Study Groups</Link>
            <Link href="/Maps" className="px-3 py-1 border rounded-md shadow-sm hover:bg-gray-10">Maps</Link>

            <div className="ml-auto flex items-center gap-3 text-sm">
              <span className="text-gray-600">Signed in as <b>{session.name}</b></span>
              {/* ✅ This is now an inline server action, safe anywhere */}
              <form action={logout}>
                <button className="px-3 py-1 border rounded-md shadow-sm hover:bg-gray-10">Logout</button>
              </form>
            </div>
          </div>
        )}
        {children}
      </body>
    </html>
  );
}
